### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by Visivel** [SteveProxy/proxy#657]
Here is the full log:

```
F:\proxytest\proxy>npm start

> steveproxy@1.0.0 start
> node --experimental-modules --experimental-json-modules --experimental-specifier-resolution=node --unhandled-rejections=warn --loader ts-node/esm ./src/index.ts

(node:15092) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15092) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
(node:15092) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(node:15092) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
file:///F:/proxytest/proxy/src/utils/getVersion.ts:12
    return versionObject[isString ? 'version' : 'minecraftVersion'] as VersionOrProtocol<V>;
                        ^
TypeError: Cannot read properties of undefined (reading 'version')
    at getVersion (file:///F:/proxytest/proxy/src/utils/getVersion.ts:12:25)
    at file:///F:/proxytest/proxy/src/config.ts:60:37
```

**Comment by Visivel** [comment]
Tried to update some dependencies, now its giving out another error

```
F:\proxytest\proxy>npm start

> steveproxy@1.0.0 start
> node --experimental-modules --experimental-json-modules --experimental-specifier-resolution=node --unhandled-rejections=warn --loader ts-node/esm ./src/index.ts

(node:12424) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12424) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
(node:12424) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(node:12424) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
TypeError: Cannot read properties of undefined (reading 'value')
    at file:///F:/proxytest/proxy/src/utils/constants.ts:26:30
```
